### PR TITLE
andrews-casandra-update2

### PR DESCRIPTION
**Pull request by Cassie-Andrews**
Updated content and styles on the "More" page to match the other pages
Just gonna continue working on formatting my images and heading a bit more

### CODE REVIEW

**Review by gabster1313 — APPROVED** [review]

**Comment by gabster1313** [comment]
when you merge double check that your css gets added,  but doesn't replace /erasethe css with Austins and I stuff

**Comment by Cassie-Andrews** [comment]
It should be all set! I didn't delete anything, I just added a section for my edits and copied your heading style into mine so it matches(:

**Comment by gabster1313** [comment]
awesome thank you so much! Also i noticed in the deployed page your images don't show up, can you try removing the slash in font of "images" and see if that changes anything?

**Comment by Cassie-Andrews** [comment]
oops, I believe I fixed it. I'm about to send my 3rd update and I believe I'm done after that one unless we see any final edits. Thanks!

**Pull request merged**
